FROM bitnami/spark:3.5.0

USER root

COPY config/spark-defaults.conf /opt/bitnami/spark/conf/

COPY requirements.txt .

USER root

RUN apt-get clean  && \
	apt-get update && \
	apt-get install -y python3-pip && \
	pip3 install --no-cache-dir -r ./requirements.txt